const translations = {
  en: { title: "SHALOM", slogan: "Shop The World. Pay With Pi.", search: "Search for anything with Pi...", banner_title: "🌍 GLOBAL PI MARKETPLACE 🌍", banner_sub: "Buy & Sell with Pi. No Banks. No Borders.", btn_shop: "Start Shopping", btn_sell: "Become a Seller", cat_title: "Shop by Category", cat1: "Fashion", cat2: "Electronics", cat3: "Digital", cat4: "Services", cat5: "Crypto", cat6: "Home", cat7: "Art", cat8: "More", featured: "🔥 Trending with Pi", empty_title: "No products yet", empty_sub: "Be the first seller!", btn_list: "List Your First Item - Free", menu_home: "Home", menu_products: "Products", menu_sell: "Sell", menu_orders: "Orders", menu_profile: "Profile" },
  sw: { title: "SHALOM", slogan: "Nunua Duniani. Lipa kwa Pi.", search: "Tafuta chochote kwa Pi...", banner_title: "🌍 SOKO LA DUNIA LA PI 🌍", banner_sub: "Nunua & Uuze kwa Pi. Hakuna Benki. Hakuna Mipaka.", btn_shop: "Anza Kununua", btn_sell: "Kua Muuzaji", cat_title: "Nunua kwa Kategoria", cat1: "Mavazi", cat2: "Vifaa", cat3: "Digital", cat4: "Huduma", cat5: "Crypto", cat6: "Nyumba", cat7: "Sanaa", cat8: "Zaidi", featured: "🔥 Zinazotrend kwa Pi", empty_title: "Hakuna bidhaa bado", empty_sub: "Kua muuzaji wa kwanza!", btn_list: "Orodhesha Bidhaa Yako - Bure", menu_home: "Nyumbani", menu_products: "Bidhaa", menu_sell: "Uza", menu_orders: "Oda", menu_profile: "Wasifu" },
  zh: { title: "SHALOM", slogan: "向世界购物，用Pi支付。", search: "用Pi搜索任何东西...", banner_title: "🌍 全球PI市场 🌍", banner_sub: "用Pi买卖。无银行。无国界。", btn_shop: "开始购物", btn_sell: "成为卖家", cat_title: "按类别购物", cat1: "时尚", cat2: "电子产品", cat3: "数码", cat4: "服务", cat5: "加密", cat6: "家居", cat7: "艺术", cat8: "更多", featured: "🔥 Pi热门", empty_title: "暂无商品", empty_sub: "成为第一个卖家！", btn_list: "免费上架您的第一个商品", menu_home: "首页", menu_products: "产品", menu_sell: "出售", menu_orders: "订单", menu_profile: "我的" },
  es: { title: "SHALOM", slogan: "Compra al Mundo. Paga con Pi.", search: "Busca cualquier cosa con Pi...", banner_title: "🌍 MERCADO GLOBAL DE PI 🌍", banner_sub: "Compra y Vende con Pi. Sin Bancos. Sin Fronteras.", btn_shop: "Empezar a Comprar", btn_sell: "Ser Vendedor", cat_title: "Comprar por Categoría", cat1: "Moda", cat2: "Electrónica", cat3: "Digital", cat4: "Servicios", cat5: "Cripto", cat6: "Hogar", cat7: "Arte", cat8: "Más", featured: "🔥 Tendencia con Pi", empty_title: "Aún no hay productos", empty_sub: "¡Sé el primer vendedor!", btn_list: "Lista tu Primer Artículo - Gratis", menu_home: "Inicio", menu_products: "Productos", menu_sell: "Vender", menu_orders: "Pedidos", menu_profile: "Perfil" },
  id: { title: "SHALOM", slogan: "Belanja Dunia. Bayar dengan Pi.", search: "Cari apapun dengan Pi...", banner_title: "🌍 MARKETPLACE PI GLOBAL 🌍", banner_sub: "Beli & Jual dengan Pi. Tanpa Bank. Tanpa Batas.", btn_shop: "Mulai Belanja", btn_sell: "Jadi Penjual", cat_title: "Belanja berdasarkan Kategori", cat1: "Fashion", cat2: "Elektronik", cat3: "Digital", cat4: "Jasa", cat5: "Crypto", cat6: "Rumah", cat7: "Seni", cat8: "Lainnya", featured: "🔥 Trending dengan Pi", empty_title: "Belum ada produk", empty_sub: "Jadilah penjual pertama!", btn_list: "Daftarkan Barang Pertama - Gratis", menu_home: "Beranda", menu_products: "Produk", menu_sell: "Jual", menu_orders: "Pesanan", menu_profile: "Profil" },
  vi: { title: "SHALOM", slogan: "Mua sắm Thế giới. Thanh toán bằng Pi.", search: "Tìm kiếm bất cứ thứ gì bằng Pi...", banner_title: "🌍 CHỢ PI TOÀN CẦU 🌍", banner_sub: "Mua & Bán bằng Pi. Không Ngân hàng. Không Biên giới.", btn_shop: "Bắt đầu mua sắm", btn_sell: "Trở thành người bán", cat_title: "Mua sắm theo danh mục", cat1: "Thời trang", cat2: "Điện tử", cat3: "Kỹ thuật số", cat4: "Dịch vụ", cat5: "Tiền điện tử", cat6: "Nhà cửa", cat7: "Nghệ thuật", cat8: "Khác", featured: "🔥 Xu hướng với Pi", empty_title: "Chưa có sản phẩm", empty_sub: "Hãy là người bán đầu tiên!", btn_list: "Đăng mục đầu tiên - Miễn phí", menu_home: "Trang chủ", menu_products: "Sản phẩm", menu_sell: "Bán", menu_orders: "Đơn hàng", menu_profile: "Hồ sơ" }
};

document.getElementById('lang-switcher').addEventListener('change', (e) => {
  const lang = e.target.value;
  document.querySelectorAll('[data-lang]').forEach(el => {
    const key = el.getAttribute('data-lang');
    if(translations[lang][key]) {
      if(el.placeholder) el.placeholder = translations[lang][key];
      else el.innerText = translations[lang][key];
    }
  });
});
